// src: https://reactnavigation.org/docs/typescript
export type RootStackParamList = {
  DashboardScreen: undefined;
  FolderStackNavigation: { screen: string; params: any };
  FolderScreen: { termID: number; folderName: string };
  SalesMockupScreen: { clear?: number; mockup?: any };
  MediaDisplayScreen: { file: any };
  VideoDisplayScreen: { file: any };
  ImageDisplayScreen: { file: any };
  ImageGalleryScreen: undefined;
  LoginScreen: undefined;
  ImageDetailsScreen: { imageSource: string };
  SignUpScreen: undefined;
  MaximizingProfitabilityScreen: undefined;
  FreestyleProfitabilityScreen: undefined;
  ReportsScreen: undefined;
  FreestyleScreen: { termID: number };
  ChannelPresentationsScreen: { termID: number };
  TestimonialsScreen: { termID: number };
  DrawerNavigation: { screen: string; params?: any };
  SaveMockupScreen: { imageUri: string; machines: any; mockup: any };
  OneButtonLoginScreen: undefined;
  SearchResultScreen: { searchText: string };
  HelpScreen: undefined;
  ActivitiesScreen: undefined;
  // Profile: undefined; // add extra parameters if needed { userId: string };
  // Users: undefined; // add extra parameters if needed { userId: string };
  // FamilyListScreen: { familyID: string };
  // ProductScreen: undefined;
  // ProductListScreen: { productID: string };
  // Cart: undefined;
  // Notification: undefined;
  // FavoriteList: undefined;
  // OrderSucess: undefined;
  // AddCreditCardScreen: undefined;
  // SignInScreen: undefined;
  // OptInScreen: undefined;
  // GrantNotificationsScreen: undefined;
  // Support: undefined;
  // Success: undefined;
  // Pickup: undefined;
  // TrackerScreen: undefined;
  // PickupSuccess: undefined;
  // OrderStatusScreen: undefined;
  // SpecialEventScreen: undefined;
  // paymentScreen: { returnTo?: string };
  // PaymentReceivedScreen: { returnTo?: string };
  // OrderHistoryScreen: undefined;
  // OrderInvoiceScreen: { orderID: string };
  // ErrorScreen: { errorText: string };
  // OrderTrackerItem: undefined;
  // CreditCardScreen: undefined;
};
